title: Apriori J104
author: <b><a href='https://gitlab.com/hsiangjenli'>Hsiang-Jen Li｜李享紝</a></b>
logo: _images/logo.png

execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://gitlab.com/hsiangjenli/apriori-j104
  path_to_book: docs
  branch: main

html:
  use_repository_button: true
  favicon: "_images/favicon.png"

sphinx:
  config:
    html_extra_path: ['_html', 'J104/Images']

parse:
  myst_enable_extensions:
    - html_image
